# Site Settings
title: Mlewand blog
tagline: a minimalist Jekyll theme
description:
  A place where I'm sharing thoughts related to my programming
  experience.
baseurl: ""
url: #"https://lenpaul.github.io"
github:
  url: #"https://lenpaul.github.io/Lagrange"
author:
  name: "Marek Lewandowski"
  email: "code@mlewandowski.com"
  twitter: "m_lewand"
  github: "mlewand"
navigation:
- title: About
  url: /about
- title: Archives
  url: /archives

paginate: 10
disqus: "mlewand-blog"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
gems: [jekyll-paginate]
