# Site Settings
title: Mlewand blog
tagline: Thoughts on programming.
description:
  A place where I'm sharing thoughts related to my programming
  experience.
baseurl: ""
url: #"https://lenpaul.github.io"
github:
  url: #"https://lenpaul.github.io/Lagrange"
author:
  name: "Marek Lewandowski"
  email: "code@mlewandowski.com"
  twitter: "m_lewand"
  github: "mlewand"
navigation:
- title: About
  url: /about
- title: Archives
  url: /archives

paginate: 10
disqus: "mlewand-blog"

responsive_image:
  # Path to the image template.
  template: _includes/responsive-image.html
  default_quality: 90

  # [Optional, Default: []]
  sizes:
    - width: 615  # [Required] How wide the resized image will be.
    - width: 800
    - width: 1200

  base_path: images/posts
  output_path_format: assets/resized/%{width}/%{basename}
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  extra_images:
    - images/*-teaser.{jpeg,jpg}


# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
gems: [jekyll-paginate, jekyll-responsive-image]
